// This file was generated by obj2h.py
// OBJ file: cobble.obj
#include "renderer/mesh.h"
#include "image.h"

vector3 vertices[] = {
    {1.0, 1.0, -1.0},
    {1.0, -1.0, -1.0},
    {1.0, 1.0, 1.0},
    {1.0, -1.0, 1.0},
    {-1.0, 1.0, -1.0},
    {-1.0, -1.0, -1.0},
    {-1.0, 1.0, 1.0},
    {-1.0, -1.0, 1.0},
};

// Texture coordinates
vector2 textureCoords[] = {
    {1.0, 0.0},
    {0.0, 1.0},
    {0.0, 0.0},
    {1.0, 0.0},
    {0.0, 1.0},
    {0.0, 0.0},
    {1.0, 0.0},
    {0.0, 1.0},
    {0.0, 0.0},
    {1.0, 0.0},
    {0.0, 0.0},
    {1.0, 0.0},
    {0.0, 1.0},
    {0.0, 0.0},
    {0.0, 1.0},
    {1.0, 1.0},
    {1.0, 1.0},
    {1.0, 1.0},
    {1.0, 1.0},
    {1.0, 1.0},
};
triangle faces[] = {
    {vertices[4], vertices[2], vertices[0], textureCoords[0], textureCoords[1], textureCoords[2]},
    {vertices[2], vertices[7], vertices[3], textureCoords[3], textureCoords[4], textureCoords[5]},
    {vertices[6], vertices[5], vertices[7], textureCoords[6], textureCoords[7], textureCoords[8]},
    {vertices[1], vertices[7], vertices[5], textureCoords[9], textureCoords[4], textureCoords[10]},
    {vertices[0], vertices[3], vertices[1], textureCoords[11], textureCoords[12], textureCoords[13]},
    {vertices[4], vertices[1], vertices[5], textureCoords[0], textureCoords[14], textureCoords[10]},
    {vertices[4], vertices[6], vertices[2], textureCoords[0], textureCoords[15], textureCoords[1]},
    {vertices[2], vertices[6], vertices[7], textureCoords[3], textureCoords[15], textureCoords[4]},
    {vertices[6], vertices[4], vertices[5], textureCoords[6], textureCoords[16], textureCoords[7]},
    {vertices[1], vertices[3], vertices[7], textureCoords[9], textureCoords[17], textureCoords[4]},
    {vertices[0], vertices[2], vertices[3], textureCoords[11], textureCoords[18], textureCoords[12]},
    {vertices[4], vertices[0], vertices[1], textureCoords[0], textureCoords[19], textureCoords[14]},
};

mesh cobble = {
    faces,
    12,
    new transformation({
        new vector3({0, 0, 0}),   // Rotation
        new vector3({0, 0, 200}), // Translation
        new vector3({100, 100, 100}),   // Scale
    }),
    &texture_image
};

// mesh *genCobble(double x, double y, double z, double scale)
// {
//     mesh *cobble = new mesh();

//     cobble->triangles = faces;
//     cobble->numTriangles = 12;

//     cobble->transformation->rotation = new vector3({0, 0, 0});
//     cobble->transformation->translation = new vector3({x * scale, y * scale, z * scale + 100});
//     cobble->transformation->scale = new vector3({scale, scale, scale});
//     return cobble;
// }