import sys

if len(sys.argv) != 2:
    print("Usage: obj2h.py <filename>")
    sys.exit(1)

filename = sys.argv[1]

# Get file name
title = filename.split(".")[:-1]

print("[INFO] Reading file:", filename)
with open(filename, "r") as f:
    data = f.read()

vs = [line for line in data.split("\n") if line.startswith("v ")]
fs = [line for line in data.split("\n") if line.startswith("f ")]

vertices = [
    [float(component.strip()) for component in components.split(" ")[1:4]]
    for components in vs
]
faces = [
    [int(component.split("/")[0]) for component in components.split(" ")[1:4]]
    for components in fs
]

print("[DATA] Vertices:", len(vertices))
print("[DATA] Faces:", len(faces))

stuff = f"""// This file was generated by obj2h.py
// OBJ file: {filename}
#include "mesh.h"
"""

# Texure coordinates
stuff += """
// Texture coordinates
point textureCoords[4] = {
    {0, 0},
    {1, 0},
    {1, 1},
    {0, 1}};

"""

stuff += "vertex vertices[] = {\n"

for vertex in vertices:
    stuff += (
        "    { "
        + str(vertex[0])
        + ", "
        + str(vertex[1])
        + ", "
        + str(vertex[2])
        + "},\n"
    )

stuff += "};\n"

# triangles
stuff += "triangle faces[] = {\n"

for face in faces:
    stuff += (
        "    { vertices["
        + str(face[0] - 1)
        + "] , vertices["
        + str(face[1] - 1)
        + "] , vertices["
        + str(face[2] - 1)
        + "] },\n"
    )

stuff += "};\n"

stuff += f"""
mesh {title[0]} = {{
    faces,
    {len(faces)},
    new vertex({{0, 0, 0}}), // Rotation
    new vertex({{0, 0, 200}}), // Translation
    10, // Scale
}};
"""

print("[INFO] Writing to file:", title[0] + ".h")
with open(title[0] + ".h", "w") as f:
    f.write(stuff)
